<a href="https://colab.research.google.com/github/hrbae/DL_Study/blob/main/DLFS_simple_net.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [54]:
import numpy as np

#import functions
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient


class simpleNet:
  def __init__(self):
    self.W = np.random.randn(2, 3)
  
  def predict(self, x):
    return np.dot(x, self.W)
  
  def loss(self, x, t):
    z=self.predict(x)
    y=softmax(z)
    loss = cross_entropy_error(y,t)

    return loss


In [55]:
net=simpleNet()
print(net.W)


[[ 0.43884409 -2.32400389  1.92142044]
 [-0.79157059 -1.83698785 -0.69599985]]


In [56]:
x=np.array([0.6, 0.9])
p=net.predict(x)
print(p)

[-0.44910707 -3.0476914   0.52645239]


In [57]:
np.argmax(p)

2

In [58]:
t=np.array([0, 0, 1])
net.loss(x,t)

0.34005197301063966